[language-server.vtsls]
command = "mise"
args = ["x", "node@24", "--", "vtsls", "--stdio"]

[language-server.vtsls.config]
typescript.tsserver.maxTsServerMemory = 8192
javascript.tsserver.maxTsServerMemory = 8192

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
validate = "on"
run = "onType"
quiet = false
nodePath = ""
rulesCustomizations = []
format = { enable = true }
problems = { shortenToSingleLine = false }
experimental = { useFlatConfig = false }
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = true }

[language-server.eslint.config.workingDirectory]
pattern = "**/tsconfig.json"

[language-server.oxlint]
command = "mise"
args = ["exec", "node@24", "--", "oxlint", "--lsp"]

[language-server.oxfmt]
command = "mise"
args = ["exec", "node@24", "--", "oxfmt", "--lsp"]

[[language]]
name = "typescript"
language-id = "typescript"
language-servers = ["vtsls", "eslint"]
formatter = { command = "eslint_d", args = ["--fix-to-stdout", "--stdin", "--stdin-filename", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "tsx"
language-id = "typescriptreact"
language-servers = ["vtsls", "eslint"]
formatter = { command = "eslint_d", args = ["--fix-to-stdout", "--stdin", "--stdin-filename", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "javascript"
language-id = "javascript"
language-servers = ["vtsls", "eslint"]
formatter = { command = "eslint_d", args = ["--fix-to-stdout", "--stdin", "--stdin-filename", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "jsx"
language-id = "javascriptreact"
language-servers = ["vtsls", "eslint"]
formatter = { command = "eslint_d", args = ["--fix-to-stdout", "--stdin", "--stdin-filename", "%{buffer_name}"] }
auto-format = true

[language-server.expert]
command = "expert"
args = ["--stdio"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "elixir"
language-servers = ["expert", "tailwindcss-ls"]
auto-format = true

[[language]]
name = "heex"
language-servers = ["expert", "tailwindcss-ls"]
auto-format = true

[language-server.tailwindcss-ls.config.tailwindCSS]
includeLanguages = { "elixir" = "html", "phoenix-heex" = "html", "*.heex" = "html" }

[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log",  "serve"]

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
auto-format = true

[language-server.phpantom]
command = "phpantom"

[[language]]
name = "php"
scope = "source.php"
roots = ["composer.json"]
file-types = ["php", "tpl"]
language-servers = ["phpantom"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]


[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/Users/owozsh/.local/share/mise/installs/node/25.8.0/lib/node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls", "tailwindcss-ls" ]
